const projectData = {
  flexin: {
    name: "Flex'In",
    heading: "FLEX'IN",
    description:
      "Flex'In is a comprehensive health and fitness management application designed to bring personal training, community engagement, and eCommerce into one connected ecosystem. Unlike traditional fitness apps, Flex'In leverages a Python-powered machine learning engine to create highly personalized workout plans tailored to each user’s fitness level, goals, available equipment, and schedule. Progress is tracked over time, giving users a clear picture of their health journey.\n\n Beyond training, Flex'In focuses heavily on social motivation. Its real-time community feed allows users to share updates, post photos, exchange tips, and engage with others through likes and comments — creating an interactive environment that keeps fitness fun and engaging. \n The platform also integrates a dedicated fitness store, where users can seamlessly browse, purchase, and manage gym-related products. Trainers and admins are provided with tools for product management, content moderation, and user oversight, ensuring smooth operations across the platform. \n Built with the MERN stack (MongoDB, Express.js, React, Node.js) and styled with Tailwind CSS, Flex'In emphasizes performance, responsiveness, and scalability. Security is enforced through JWT-based authentication with role-based permissions (User, Trainer, Admin), making sure that sensitive data and operations remain protected.\n Overall, Flex'In demonstrates the power of combining AI-driven personalization, full-stack engineering, and community-first design to create a holistic platform for modern fitness enthusiasts.",
    client: "Campus Project",
    role: "Frontend Development",
    technologies: "React Js, Node Js,\nTailwind CSS",
    type: "Web Development",
    duration: "5 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/Flex-in",
    screenshots: [
      "images/FlexIn/1.jpeg",
      "images/FlexIn/2.jpeg",
      "images/FlexIn/3.jpeg",
      "images/FlexIn/4.jpeg",
      "images/FlexIn/5.jpeg",
      "images/FlexIn/6.jpeg",
      "images/FlexIn/7.jpeg",
      "images/FlexIn/8.jpeg",
      "images/FlexIn/9.jpeg",
      "images/FlexIn/10.jpeg",
    ],
    prevProject: "hms",
    nextProject: "crasauto",
  },
  crasauto: {
    name: "Cras Auto",
    heading: "CRAS AUTO",
    description:
      "CRAS Auto is a web-based automobile management system developed as part of a university web development course to streamline operations for an imaginary auto service business. The system, built with PHP, MySQL, JavaScript, and Bootstrap, enables efficient handling of customers, vehicles, services, billing, and inventory through a centralized platform. It includes features such as customer management with service history, vehicle and service tracking, invoice and payment handling, and inventory management for spare parts, while also supporting multiple user roles like admin, mechanic, cashier, and customer with role-specific permissions. For this project, I contributed as the backend developer, focusing on database design, server-side logic, and system integration to ensure smooth functionality and scalability.",
    client: "Campus Project",
    role: "Frontend Developer",
    technologies: "Php\nHTML\nCSS\nJavaScript\nMySQL",
    type: "Web App Development",
    duration: "4 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/AutoMobile-Service-System",
    screenshots: [
      "images/Cras Auto System/1.jpeg",
      "images/Cras Auto System/2.jpeg",
      "images/Cras Auto System/3.jpeg",
      "images/Cras Auto System/4.jpeg",
      "images/Cras Auto System/5.jpeg",
      "images/Cras Auto System/6.jpeg",
    ],
    prevProject: "flexin",
    nextProject: "hms",
  },
  hms: {
    name: "Hospital Management System",
    heading: "HOSPITAL MANAGEMENT SYSTEM",
    description:
      "The Hospital Management System (HMS) is a comprehensive desktop-based application designed to digitalize and simplify the everyday operations of a hospital. It provides an integrated platform to manage patients, doctors, staff, and administrative workflows, thereby reducing manual effort and increasing overall efficiency. The system is divided into three major modules: the Receptionist Portal, which is responsible for patient registration, appointment booking, admission and discharge handling, and maintaining patient records; the Doctor Portal, which allows doctors to view and update patient medical histories, prescribe treatments, check diagnostic details, and manage their schedules; and the Admin Portal, which provides administrators with the ability to oversee hospital activities, manage staff accounts, monitor resources, and generate analytical reports. The project is developed using C# with the .NET Framework in a Windows Forms environment, ensuring a robust and user-friendly graphical interface. For the backend, MySQL is used as the database management system, offering reliable data storage, fast retrieval, and secure access to sensitive patient information. The system also incorporates role-based authentication to ensure confidentiality and data integrity. By combining these technologies, the HMS not only streamlines the workflow of different departments but also minimizes human errors, reduces paperwork, improves communication between medical staff and patients, and enhances the overall quality of healthcare services delivered by the hospital.",
    client: "Campus Project",
    role: "Full Stack Developer",
    technologies: "C#, .NET, MYSQL",
    type: "Desktop Application",
    duration: "1 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/Hospital-Management-System",
    screenshots: [
      "images/HMS/1.png",
      "images/HMS/2.png",
      "images/HMS/3.png",
      "images/HMS/4.png",
      "images/HMS/5.png",
      "images/HMS/6.png",
      "images/HMS/7.png",
      "images/HMS/8.png",
    ],
    prevProject: "crasauto",
    nextProject: "flexin",
  },
  codemize: {
    name: "CodemiZe 2.0",
    heading: "CODEMIZE 2.0",
    description:
      "I designed the User Interface (UI) for the CodemiZe 2.0 Competition Management System, a platform developed to manage one of Sri Lanka’s leading inter-school coding competitions. The system was structured with three main portals—Student Portal, Admin Portal, and Judge Board Portal—each tailored to provide an intuitive experience for its specific users. Through the Student Portal, participants could register, access the five competition games, view progress, and track their scores. The Admin Portal allowed organizers to manage participants, monitor events, and update schedules, while the Judge Board Portal enabled judges to evaluate submissions and assign scores in real time. My design emphasized clean navigation, modern aesthetics, and consistency across all modules, ensuring the platform was both functional and engaging. By combining usability with a professional look, the CodemiZe 2.0 system enhanced the overall competition experience for students, organizers, and judges alike.",
    client: "BCI Coding Club",
    role: "UI / UX Designer",
    technologies: "Figma | Photoshop",
    type: "UI Design",
    duration: "1 Week",
    category: "UI / UX Design",
    githubLink: "https://github.com/surajmalaka29/fullstack-web-app",
    figmaLink:
      "https://www.figma.com/team_invite/redeem/HxLF4dTRv8xDPLbfl59a1l",
    screenshots: [
      "images/Codemize UI/1.png",
      "images/Codemize UI/2.png",
      "images/Codemize UI/3.png",
      "images/Codemize UI/4.png",
      "images/Codemize UI/5.png",
      "images/Codemize UI/6.png",
      "images/Codemize UI/7.png",
      "images/Codemize UI/8.png",
    ],
    prevProject: "lsnursery",
    nextProject: "flexinUI",
  },
  flexinUI: {
    name: "Flex'In UI Design",
    heading: "FLEXIN UI DESIGN",
    description:
      "I designed the UI/UX for Flex’In with a strong focus on delivering a seamless and engaging user experience that aligns with the platform’s vision of combining fitness management, community interaction, and eCommerce. Using Figma, I created wireframes, prototypes, and a scalable design system to ensure smooth user flows, clear navigation, and consistency across all pages. I also incorporated Photoshop to enhance the visual identity with polished graphics, branding elements, and imagery that resonate with fitness enthusiasts. The design emphasizes modern aesthetics, responsive layouts, and accessibility, making it easy for users to track workouts, connect with the community, and shop for fitness products without friction. Overall, my goal was to craft a dynamic and intuitive interface that not only looks appealing but also motivates users to stay active, engaged, and connected through Flex’In.",
    client: "Campus Project",
    role: "UI / UX Designer",
    technologies: "Figma | Photoshop",
    type: "UI Design",
    duration: "1 Months",
    category: "UI / UX Design",
    githubLink: "https://github.com/surajmalaka29/fullstack-web-app",
    figmaLink:
      "https://www.figma.com/team_invite/redeem/NfbYxkE5nvrsQC1cEQhg0n",
    screenshots: [
      "images/FlexIn/1.jpeg",
      "images/FlexIn/2.jpeg",
      "images/FlexIn/3.jpeg",
      "images/FlexIn/4.jpeg",
      "images/FlexIn/5.jpeg",
      "images/FlexIn/6.jpeg",
      "images/FlexIn/7.jpeg",
      "images/FlexIn/8.jpeg",
      "images/FlexIn/9.jpeg",
      "images/FlexIn/10.jpeg",
      "images/FlexIn/11.png",
    ],
    prevProject: "codemize",
    nextProject: "crasautoUI",
  },
  crasautoUI: {
    name: "Cras Auto UI Design",
    heading: "CRAS AUTO UI DESIGN",
    description:
      "I designed the UI/UX for CRAS Auto, a web-based automobile management system developed as part of a university web development course. The system was built with PHP, MySQL, JavaScript, and Bootstrap to streamline operations for an imaginary auto service business, covering customer management, vehicle and service tracking, billing, and inventory. My role focused on creating an intuitive and visually consistent interface across multiple user roles—admin, mechanic, cashier, and customer—each with tailored dashboards and permissions. I prioritized user-centered design, ensuring smooth navigation, responsive layouts, and clear data presentation to enhance usability and accessibility. By balancing functionality with a modern aesthetic, my design contributed to a seamless digital experience that improved the overall efficiency and usability of the system.",
    client: "Campus Project",
    role: "UI Designer",
    technologies: "Figma | Photoshop",
    type: "UI Design",
    duration: "1 Months",
    category: "UI / UX Design",
    githubLink: "https://github.com/surajmalaka29/ecommerce-platform",
    figmaLink:
      "https://www.figma.com/team_invite/redeem/zz5KXfrDEpKQzotipSRCwe",
    screenshots: [
      "images/Cras Auto UI/1.png",
      "images/Cras Auto UI/2.png",
      "images/Cras Auto UI/3.png",
      "images/Cras Auto UI/4.png",
      "images/Cras Auto UI/5.png",
      "images/Cras Auto UI/6.png",
      "images/Cras Auto UI/7.png",
      "images/Cras Auto UI/8.png",
    ],
    prevProject: "flexinUI",
    nextProject: "hmsUI",
  },
  hmsUI: {
    name: "Hospital Management System UI Design",
    heading: "HOSPITAL MANAGEMENT SYSTEM UI DESIGN",
    description:
      "The User Interface (UI) and User Experience (UX) of the Hospital Management System were carefully designed to ensure simplicity, clarity, and efficiency in hospital operations. The design process focused on creating an intuitive interface that allows users such as receptionists, doctors, and administrators to navigate through the system with ease. The layout of each portal was structured to minimize complexity, with well-organized menus, clear labeling, and consistent color schemes that improve readability and usability. Tools like Figma were used to design wireframes, prototypes, and interactive mockups, allowing the system flow to be visualized and refined before development. In addition, Adobe Photoshop was used to enhance the design by creating polished icons, graphics, and visual elements, giving the system a professional and modern look. The UI emphasizes accessibility with simple navigation, responsive layouts, and a clean dashboard-style design, ensuring that users can quickly perform tasks such as patient registration, record retrieval, appointment scheduling, and report generation without confusion. Overall, the UI/UX design combines functionality with aesthetics, ensuring that the system is not only visually appealing but also user-friendly and efficient for everyday hospital use.",
    client: "Campus Project",
    role: "UI Designer",
    technologies: "Figma | Photoshop",
    type: "UI Design",
    duration: "2 Weeks",
    category: "UI / UX Design",
    githubLink: "https://github.com/surajmalaka29/ecommerce-platform",
    figmaLink:
      "https://www.figma.com/team_invite/redeem/Exran3FaZxhnrLeYsDEI9D",
    screenshots: [
      "images/HMS/1.PNG",
      "images/HMS/2.PNG",
      "images/HMS/3.PNG",
      "images/HMS/4.PNG",
      "images/HMS/5.PNG",
      "images/HMS/6.PNG",
      "images/HMS/7.PNG",
      "images/HMS/8.PNG",
      "images/HMS/9.png",
    ],
    prevProject: "crasautoUI",
    nextProject: "lsnursery",
  },
  lsnursery: {
    name: "Little Sprouts Nursery",
    heading: "LITTLE SPROUTS NURSERY",
    description:
      "The Little Sprouts Nursery website features a vibrant, child-friendly UI/UX design crafted in Figma and Photoshop. The homepage showcases a warm teal background with cloud motifs, featuring two diverse children with books and backpacks, and a prominent 'Explore' CTA in orange. The navigation bar is clean and sticky, with options like Home, Curriculum, Admissions, About Us, and Contact. The About Us page uses a wavy orange header with a photo of a child holding a book, paired with the 'Top Choice for Children' tagline and contact details. The Contact page includes a sidebar with icons for phone, email, and location, alongside a simple form with an orange 'Submit' button. The Blog page offers a search bar and a grid layout for posts, maintaining the wavy header design. The overall aesthetic blends playful curves with a professional layout, ensuring accessibility and engagement for parents.",
    client: "Cloud Shift",
    role: "UI Designer",
    technologies: "Figma | Photoshop",
    type: "UI Design",
    duration: "1 Week",
    category: "UI / UX Design",
    figmaLink:
      "https://www.figma.com/team_invite/redeem/JvQKVPJwjtUWfhLoysiEQ3",
    githubLink: "https://github.com/surajmalaka29/ecommerce-platform",
    screenshots: [
      "images/UK Project/1.png",
      "images/UK Project/2.png",
      "images/UK Project/3.png",
      "images/UK Project/4.png",
      "images/UK Project/5.png",
      "images/UK Project/6.png",
    ],
    prevProject: "hmsUI",
    nextProject: "flexinUI",
  },
};
//   project6: {
//     name: "Graphic Design",
//     heading: "GRAPHIC DESIGN",
//     description:
//       "A collection of graphic design work including brand identity, print materials, and digital assets. This project showcases creativity and technical skills in visual design and brand communication.",
//     client: "Various Clients",
//     role: "Graphic Designer\nBrand Strategist",
//     technologies: "Adobe Photoshop\nAdobe Illustrator\nAdobe InDesign\nFigma",
//     type: "Graphic Design",
//     duration: "Ongoing",
//     category: "Graphic Design",
//     githubLink: "https://github.com/surajmalaka29/graphic-design-portfolio",
//     screenshots: [
//       "images/flex'in.jpeg",
//       "images/MacBook Air - 4.png",
//       "images/MacBook Air - 3.png",
//     ],
//     prevProject: "project5",
//     nextProject: "flexin",
//   },
// };
