const projectData = {
  flexin: {
    name: "Flex'In",
    heading: "FLEX'IN",
    description:
      "A modern fitness tracking web application designed to help users monitor their workout routines and progress. Built with a focus on user experience and responsive design, this project showcases modern web development practices and clean UI design principles.",
    client: "Campus Project",
    role: "UI / UX Design\nFrontend Development",
    technologies: "HTML5, SCSS\nTailwind CSS\nFigma",
    type: "Web Development",
    duration: "5 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/flexin-app",
    screenshots: [
      "images/flex'in.jpeg",
      "images/MacBook Air - 3.png",
      "images/MacBook Air - 4.png",
    ],
    prevProject: "hms",
    nextProject: "crasauto",
  },
  crasauto: {
    name: "Cras Auto",
    heading: "CRAS AUTO",
    description:
      "A comprehensive mobile application built for both iOS and Android platforms using React Native. This project focused on creating a seamless user experience with robust backend integration and real-time data synchronization.",
    client: "Campus Project",
    role: "Full-Stack Developer\nUI Designer",
    technologies: "Php\nHTML\nCSS\nJavaScript\nMySQL",
    type: "Web App Development",
    duration: "4 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/mobile-app-project",
    screenshots: [
      "images/MacBook Air - 4.png",
      "images/flex'in.jpeg",
      "images/MacBook Air - 3.png",
    ],
    prevProject: "flexin",
    nextProject: "hms",
  },
  hms: {
    name: "Hospital Management System",
    heading: "HOSPITAL MANAGEMENT SYSTEM",
    description:
      "A comprehensive design system and user interface design project focused on creating intuitive and accessible user experiences. This project involved extensive user research, wireframing, prototyping, and usability testing.",
    client: "Campus Project",
    role: "UI/UX Designer\nFull Stack Developer",
    technologies: "Figma\nAdobe XD\nSketch\nInVision",
    type: "Desktop Application",
    duration: "1 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/ui-ux-design-system",
    screenshots: [
      "images/flex'in.jpeg",
      "images/MacBook Air - 3.png",
      "images/MacBook Air - 4.png",
    ],
    prevProject: "crasauto",
    nextProject: "flexin",
  },
  codemize: {
    name: "CodemiZe 2.0",
    heading: "CODEMIZE 2.0",
    description:
      "A full-stack web application built with modern technologies, featuring real-time data processing, user authentication, and responsive design. This project demonstrates proficiency in both frontend and backend development.",
    client: "Campus Project",
    role: "UI / UX Designer",
    technologies: "Figma\n Photoshop",
    type: "UI Design",
    duration: "1 Week",
    category: "UI / UX Design",
    githubLink: "https://github.com/surajmalaka29/fullstack-web-app",
    figmaLink: "https://www.figma.com/design/example-codemize-ui-design",
    screenshots: [
      "images/MacBook Air - 3.png",
      "images/flex'in.jpeg",
      "images/MacBook Air - 4.png",
    ],
    prevProject: "lsnursery",
    nextProject: "flexinUI",
  },
  flexinUI: {
    name: "Flex'In UI Design",
    heading: "FLEXIN UI DESIGN",
    description:
      "A full-stack web application built with modern technologies, featuring real-time data processing, user authentication, and responsive design. This project demonstrates proficiency in both frontend and backend development.",
    client: "Campus Project",
    role: "UI / UX Designer",
    technologies: "Figma\n Photoshop",
    type: "UI Design",
    duration: "1 Months",
    category: "UI / UX Design",
    githubLink: "https://github.com/surajmalaka29/fullstack-web-app",
    figmaLink: "https://www.figma.com/design/example-flexin-ui-design",
    screenshots: [
      "images/MacBook Air - 3.png",
      "images/flex'in.jpeg",
      "images/MacBook Air - 4.png",
    ],
    prevProject: "codemize",
    nextProject: "crasautoUI",
  },
  crasautoUI: {
    name: "Cras Auto UI Design",
    heading: "CRAS AUTO UI DESIGN",
    description:
      "A complete e-commerce solution with modern design and advanced functionality including payment integration, inventory management, and admin dashboard. Built with scalability and performance in mind.",
    client: "Campus Project",
    role: "UI Designer",
    technologies: "Figma\n Photoshop",
    type: "UI Design",
    duration: "1 Months",
    category: "UI / UX Design",
    githubLink: "https://github.com/surajmalaka29/ecommerce-platform",
    figmaLink: "https://www.figma.com/design/example-crasauto-ui-design",
    screenshots: [
      "images/MacBook Air - 4.png",
      "images/MacBook Air - 3.png",
      "images/flex'in.jpeg",
    ],
    prevProject: "flexinUI",
    nextProject: "hmsUI",
  },
  hmsUI: {
    name: "Hospital Management System UI Design",
    heading: "HOSPITAL MANAGEMENT SYSTEM UI DESIGN",
    description:
      "A complete e-commerce solution with modern design and advanced functionality including payment integration, inventory management, and admin dashboard. Built with scalability and performance in mind.",
    client: "Campus Project",
    role: "UI Designer",
    technologies: "Figma\n Photoshop",
    type: "UI Design",
    duration: "2 Weeks",
    category: "UI / UX Design",
    githubLink: "https://github.com/surajmalaka29/ecommerce-platform",
    figmaLink: "https://www.figma.com/design/example-hms-ui-design",
    screenshots: [
      "images/MacBook Air - 4.png",
      "images/MacBook Air - 3.png",
      "images/flex'in.jpeg",
    ],
    prevProject: "crasautoUI",
    nextProject: "lsnursery",
  },
  lsnursery: {
    name: "Little Sprouts Nursery",
    heading: "LITTLE SPROUTS NURSERY",
    description:
      "A complete e-commerce solution with modern design and advanced functionality including payment integration, inventory management, and admin dashboard. Built with scalability and performance in mind.",
    client: "Campus Project",
    role: "UI Designer",
    technologies: "Figma\n Photoshop",
    type: "UI Design",
    duration: "1 Months",
    category: "UI / UX Design",
    figmaLink: "https://www.figma.com/design/example-little-sprouts-nursery-ui",
    githubLink: "https://github.com/surajmalaka29/ecommerce-platform",
    screenshots: [
      "images/MacBook Air - 4.png",
      "images/MacBook Air - 3.png",
      "images/flex'in.jpeg",
    ],
    prevProject: "hmsUI",
    nextProject: "flexinUI",
  },
  project6: {
    name: "Graphic Design",
    heading: "GRAPHIC DESIGN",
    description:
      "A collection of graphic design work including brand identity, print materials, and digital assets. This project showcases creativity and technical skills in visual design and brand communication.",
    client: "Various Clients",
    role: "Graphic Designer\nBrand Strategist",
    technologies: "Adobe Photoshop\nAdobe Illustrator\nAdobe InDesign\nFigma",
    type: "Graphic Design",
    duration: "Ongoing",
    category: "Graphic Design",
    githubLink: "https://github.com/surajmalaka29/graphic-design-portfolio",
    screenshots: [
      "images/flex'in.jpeg",
      "images/MacBook Air - 4.png",
      "images/MacBook Air - 3.png",
    ],
    prevProject: "project5",
    nextProject: "flexin",
  },
};
