const projectData = {
  flexin: {
    name: "Flex'In",
    heading: "FLEX'IN",
    description:
      "A modern fitness tracking web application designed to help users monitor their workout routines and progress. Built with a focus on user experience and responsive design, this project showcases modern web development practices and clean UI design principles.",
    client: "Campus Project",
    role: "UI / UX Design\nFrontend Development",
    technologies: "HTML5, SCSS\nTailwind CSS\nFigma",
    type: "Web Development",
    duration: "5 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/flexin-app",
    screenshots: [
      "images/flex'in.jpeg",
      "images/MacBook Air - 3.png",
      "images/MacBook Air - 4.png",
    ],
    prevProject: "project6",
    nextProject: "project2",
  },
  project2: {
    name: "Mobile App",
    heading: "MOBILE APP",
    description:
      "A comprehensive mobile application built for both iOS and Android platforms using React Native. This project focused on creating a seamless user experience with robust backend integration and real-time data synchronization.",
    client: "Startup Client",
    role: "Full-Stack Developer\nUI Designer",
    technologies: "React Native\nFirebase\nNode.js",
    type: "Mobile App Development",
    duration: "4 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/mobile-app-project",
    screenshots: [
      "images/MacBook Air - 4.png",
      "images/flex'in.jpeg",
      "images/MacBook Air - 3.png",
    ],
    prevProject: "flexin",
    nextProject: "project3",
  },
  project3: {
    name: "UI/UX Design",
    heading: "UI/UX DESIGN",
    description:
      "A comprehensive design system and user interface design project focused on creating intuitive and accessible user experiences. This project involved extensive user research, wireframing, prototyping, and usability testing.",
    client: "Design Agency",
    role: "UI/UX Designer\nUser Researcher",
    technologies: "Figma\nAdobe XD\nSketch\nInVision",
    type: "UI/UX Design",
    duration: "3 Months",
    category: "UI / UX Design",
    githubLink: "https://github.com/surajmalaka29/ui-ux-design-system",
    screenshots: [
      "images/flex'in.jpeg",
      "images/MacBook Air - 3.png",
      "images/MacBook Air - 4.png",
    ],
    prevProject: "project2",
    nextProject: "project4",
  },
  project4: {
    name: "Web App",
    heading: "WEB APP",
    description:
      "A full-stack web application built with modern technologies, featuring real-time data processing, user authentication, and responsive design. This project demonstrates proficiency in both frontend and backend development.",
    client: "Tech Company",
    role: "Full-Stack Developer\nSystem Architect",
    technologies: "React.js\nNode.js\nMongoDB\nExpress.js",
    type: "Web Development",
    duration: "6 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/fullstack-web-app",
    screenshots: [
      "images/MacBook Air - 3.png",
      "images/flex'in.jpeg",
      "images/MacBook Air - 4.png",
    ],
    prevProject: "project3",
    nextProject: "project5",
  },
  project5: {
    name: "E-Commerce",
    heading: "E-COMMERCE",
    description:
      "A complete e-commerce solution with modern design and advanced functionality including payment integration, inventory management, and admin dashboard. Built with scalability and performance in mind.",
    client: "Retail Business",
    role: "Lead Developer\nUI Designer",
    technologies: "Next.js\nStripe API\nPostgreSQL\nTailwind CSS",
    type: "E-Commerce Development",
    duration: "8 Months",
    category: "App Development",
    githubLink: "https://github.com/surajmalaka29/ecommerce-platform",
    screenshots: [
      "images/MacBook Air - 4.png",
      "images/MacBook Air - 3.png",
      "images/flex'in.jpeg",
    ],
    prevProject: "project4",
    nextProject: "project6",
  },
  project6: {
    name: "Graphic Design",
    heading: "GRAPHIC DESIGN",
    description:
      "A collection of graphic design work including brand identity, print materials, and digital assets. This project showcases creativity and technical skills in visual design and brand communication.",
    client: "Various Clients",
    role: "Graphic Designer\nBrand Strategist",
    technologies: "Adobe Photoshop\nAdobe Illustrator\nAdobe InDesign\nFigma",
    type: "Graphic Design",
    duration: "Ongoing",
    category: "Graphic Design",
    githubLink: "https://github.com/surajmalaka29/graphic-design-portfolio",
    screenshots: [
      "images/flex'in.jpeg",
      "images/MacBook Air - 4.png",
      "images/MacBook Air - 3.png",
    ],
    prevProject: "project5",
    nextProject: "flexin",
  },
};
